/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniTest_JniTest */

#ifndef _Included_JniTest_JniTest
#define _Included_JniTest_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniTest_JniTest
 * Method:    PrintHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JniTest_JniTest_PrintHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
